# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f377a7bf95796ac51715b868db9a20c89b02aa2453a4ca8406fa9b1a92cebde669271b20853ea8924aa7cf2baf57c3d5b1341cab013c7ddf7b8e5ddc5a9206

test:
  secret_key_base: 3c8b28d198b0b738bd565951fcbfc8b64a5b7d7f5bf472e4ecaffc7cbe79f908621ca523eea37423500229c14faacce577feb3aa87fd72ad27c80f227aad67a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
